### ISSUE TITLE
MG in FCOS

### ISSUE THREAD

**Issue by Tangzhaotz** [ZHANGHeng19931123/MutualGuide#1]
where can i find the model in FCOS？

**Comment by ZHANGHeng19931123** [comment]
Hello, this project does not include MG-FCOS, which is a separate project modified from this project.

**Comment by ZHANGHeng19931123** [comment]
MG-FCOS works worse than MG-RetinaNet on PASCAL VOC dataset, I hesitate to provide code for MG-FCOS

**Comment by Tangzhaotz** [comment]
thank you
