### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by NHW2017** [ZHANGHeng19931123/MutualGuide#2]
HELLO! I have read the paper in detail, but I still don't understand the logical relationship between IOUanchor and IOUregssion, IOUamplified. I have also read your article on Zhihu, and I have roughly understood some ideas, but it seems that the logic in the paper is not quite the same, so could you please explain it briefly, thank you very much

**Comment by ZHANGHeng19931123** [comment]
Hello, thank you for your interest.
IoUanchor is the IoU between predefined anchor boxes and gt boxes;
IoUregression is the IoU between regressed boxes (mode localization prediction) and gt boxes;
IoUamplified is the IoUanchor amplified by the correct classification score (model classification prediction).
